#!/usr/bin/env python3
"""Derive DSP metadata from the same manifest used by Schwung's UI."""
import json
from pathlib import Path
root = Path(__file__).resolve().parents[1]
m = json.loads((root / 'src/module.json').read_text())
parts = ['/* Generated by scripts/generate_metadata.py; edit module.json. */']
for name, obj in [('stranger_chain_params', m['capabilities']['chain_params']),
                  ('stranger_ui_hierarchy', m['capabilities']['ui_hierarchy'])]:
    payload = json.dumps(obj, separators=(',', ':'))
    parts.append(f'static const char {name}[] = {json.dumps(payload)};')
(root / 'src/metadata.h').write_text('\n'.join(parts) + '\n')
